include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
    todo: ignore
    missing_return: error
    dead_code: info

  exclude:
    - "lib/di/di.config.dart"
    - "**/*.config.dart"
    - "lib/i18n/**"
    - "lib/generated/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "libraries/**"
    - "flutter/**"
    - "test/**"
    - "android/**"
    - "ios/**"

linter:
  rules:
    sort_pub_dependencies: true
    prefer_interpolation_to_compose_strings: true
    recursive_getters: true
    public_member_api_docs: false
    prefer_relative_imports: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false
    avoid_types_on_closure_parameters: true
    always_declare_return_types: true
    avoid_catches_without_on_clauses: false
    flutter_style_todos: true
    avoid_print: true
    use_build_context_synchronously: true
    no_leading_underscores_for_local_identifiers: true
    collection_methods_unrelated_type: true
    implicit_call_tearoffs: true
    use_super_parameters: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    curly_braces_in_flow_control_structures: true
    sort_child_properties_last: true
    require_trailing_commas: true
    sort_unnamed_constructors_first: true
    depend_on_referenced_packages: false
    constant_identifier_names: false
    sort_constructors_first: true
