name: big_apple
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0 <4.0.0"

dependencies:
  appwrite: 11.0.1
  bloc_concurrency: 0.2.3
  collection: 1.18.0
  dotted_border: 2.1.0
  firebase_core: 2.25.4
  flame: 1.16.0
  flame_audio: 2.10.0
  flame_tiled: 1.19.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_flip_card: 0.0.5
  flutter_svg: 2.0.10+1
  get_it: 7.6.7
  injectable: 2.3.2
  intl: 0.19.0
  json_annotation: 4.8.1
  shared_preferences: 2.2.2

dev_dependencies:
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: 2.4.1
  json_serializable: 6.7.1

flutter_gen:
  output: lib/generated
  line_length: 120
  integrations:
    flutter_svg: true
    langs: false
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/tiles/

  fonts:
    - family: ProtestStrike
      fonts:
        - asset: fonts/ProtestStrike-Regular.ttf
