// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoV2y5abOePE_ErlSydATfd4ZyOQBz3RY',
    appId: '1:304727663020:web:a4bd54a6c4c90723631a09',
    messagingSenderId: '304727663020',
    projectId: 'big-apple-game',
    authDomain: 'big-apple-game.firebaseapp.com',
    storageBucket: 'big-apple-game.appspot.com',
    measurementId: 'G-H4RS3TL9VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBySwP-7OiC9yvR7JC_LO-qHNLpKFkU2_4',
    appId: '1:304727663020:android:bd8e45f1f32f616f631a09',
    messagingSenderId: '304727663020',
    projectId: 'big-apple-game',
    storageBucket: 'big-apple-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRm6KWl2S9h691P6gqIg0HxwFwpR9w1Zw',
    appId: '1:304727663020:ios:657fd898bece554e631a09',
    messagingSenderId: '304727663020',
    projectId: 'big-apple-game',
    storageBucket: 'big-apple-game.appspot.com',
    iosBundleId: 'one.regium.eca',
  );
}
